name: Build Backpack Build Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install
        run: npm install
      - name: Build production bundle
        run: npm run all
      - name: Commit
        run: |
          git add dist/*
          git commit -m "Update GH Actions code"
          git push