name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          branch: ${{ secrets.. }}
          netlify_site_id: ${{ secrets.. }}
          netlify_auth_token: ${{ secrets.. }}
          npm_auth_token: ${{ secrets.. }}
          backpack_api_secret_token: ${{ secrets.. }}
          backpack_site_id: ${{ secrets.. }}
          cms_content_token: ${{ secrets.. }}
          cms_management_token: ${{ secrets.. }}
          shopify_domain: ${{ secrets.. }}
          shopify_admin_api_token: ${{ secrets.. }}
          shopify_storefront_api_token: ${{ secrets.. }}
          site_url: ${{ secrets.. }}
          pack_api_url: ${{ secrets.. }}
          auto_deploy_netlify_disabled: ${{ secrets.. }}
